---

- hosts: servers
  become: true
  tasks:
  - name: Update and upgrade apt packages

    apt:
      update_cache: yes
      upgrade: "yes"

  - name: Install GPG & git
    apt:
      name: gnupg,git
      update_cache: yes
      state: present

  - name: Install the gpg key for nodejs LTS
    apt_key:
      url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
      state: present

  - name: Install the nodejs LTS repos
    apt_repository:
      repo: "deb https://deb.nodesource.com/node_18.x focal main"
      state: present
      update_cache: yes

  - name: Install NodeJS
    apt:
      name: nodejs
      state: latest
 
  - name: Install Typescript via npm
    npm:
      name: "typescript"
      global: true
      version: "latest"
  - name: Install PM2 via npm
    npm:
      name: "pm2"
      global: true

  - name: Clone tf2autobot repo 
    ansible.builtin.git:
      repo: "https://github.com/TF2Autobot/tf2autobot.git" 
      dest: /home/{{ansible_user}}/tf2autobot
      clone: yes
      update: yes 
     

  - name: change directory to autobot 
    command: ls 
    args:
      chdir: /home/{{ansible_user}}/tf2autobot

  - name: Install tf2autobot NPM dependanceies 
    community.general.npm:
      
      path: /home/{{ansible_user}}/tf2autobot/src


  - name: Build tf2autobot

    command: npm run build
    args: 
      chdir: /home/{{ansible_user}}/tf2autobot
  
  - name: Copying ecosystem.json to server 
    copy:
      src: "{{local_ecosytemjson_path}}"
      dest: /home/{{ansible_user}}/tf2autobot/ecosystem.json

  - name: Running tf2autobot
    command: pm2 start ecosystem.json && pm2 save
    register: command_result
    failed_when: "'failed' in command_result.stderr"
    args: 
      chdir: /home/{{ansible_user}}/tf2autobot








